modLoader = "javafml"
loaderVersion = "[2,)"
license = "GPL v3.0"
issueTrackerURL = "https://github.com/SevenZeroMeowTeam/crafting-dead/issues"

[[mods]]
modId = "craftingdead"
version = "${file.jarVersion}"
displayName = "Crafting Dead"
displayURL = "https://github.com/SevenZeroMeowTeam/crafting-dead"
authors = "Sm0keySa1m0n, Arzio"
credits = "Sm0keySa1m0n, Arzio, F3RULLO14, SevenZeroMeowTeam, miaoxing"
description = '''
    The Minecraft zombie survival mod.
    '''

[[dependencies.craftingdead]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftingdead]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftingdead]]
modId = "geckolib"
type = "required"
versionRange = "[4.7.0,)"
ordering = "NONE"
side = "BOTH"
