plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    maven { 
        name 'neoforge'
        url 'https://maven.neoforged.net/releases/'
    }
    mavenCentral()
}

dependencies {
    implementation group: 'net.neoforged', name: 'moddev-gradle', version: '2.0.80'
    implementation group: 'gradle.plugin.org.cadixdev.gradle', name: 'licenser', version: '0.6.1'
}