/*
 * Crafting Dead
 * Copyright (C) 2022  NexusNode LTD
 *
 * This Non-Commercial Software License Agreement (the "Agreement") is made between
 * you (the "Licensee") and NEXUSNODE (BRAD HUNTER). (the "Licensor").
 * By installing or otherwise using Crafting Dead (the "Software"), you agree to be
 * bound by the terms and conditions of this Agreement as may be revised from time
 * to time at Licensor's sole discretion.
 *
 * If you do not agree to the terms and conditions of this Agreement do not download,
 * copy, reproduce or otherwise use any of the source code available online at any time.
 *
 * https://github.com/nexusnode/crafting-dead/blob/1.18.x/LICENSE.txt
 *
 * https://craftingdead.net/terms.php
 */

package com.craftingdead.core.quality;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * TaCZ（Timeless and Classics Zero）1.1.x 默认枪包（tacz_default_gunpack）的静态枪械数据。
 *
 * <p>数据来源：从 TaCZ 1.1.8 默认枪包解包导出——
 * <ul>
 *   <li>枪械弹药与弹匣容量：{@code data/tacz/data/guns/*_data.json} 的 {@code ammo} / {@code ammo_amount}</li>
 *   <li>每把枪可装配件：{@code data/tacz/tacz_tags/attachments/allow_attachments/*.json} 标签解析后的
 *       具体配件物品 id（已过滤弹药改装件 {@code ammo_mod_*}）</li>
 * </ul>
 *
 * <p>用于新手奖励：随机抽取一把枪械并附上其对应可装配件（备件）。
 * 未安装 TaCZ 或物品不存在时由调用方（{@link QualityHelper}）安全降级为空栈。
 */
public final class TaCZGunData {

  private TaCZGunData() {}

  /** 一把枪的静态规格。 */
  public record GunSpec(String ammoId, int ammoAmount, List<String> attachments) {}

  private static final Map<String, GunSpec> GUNS = buildGuns();

  /** 全部可随机抽取的枪械 id（不包含榴弹发射器 / 火箭筒 / 机枪等无常规配件的枪）。 */
  public static java.util.Set<String> getGunIds() {
    return GUNS.keySet();
  }

  /** 指定枪械的弹药 id（如 "tacz:762x39"），未知枪械返回 null。 */
  public static String getAmmoId(String gunId) {
    GunSpec spec = GUNS.get(gunId);
    return spec == null ? null : spec.ammoId();
  }

  /** 指定枪械的弹匣容量（预装填弹药数），未知枪械返回 0。 */
  public static int getAmmoAmount(String gunId) {
    GunSpec spec = GUNS.get(gunId);
    return spec == null ? 0 : spec.ammoAmount();
  }

  /** 指定枪械的可装配件 id 列表（对应备件池），未知枪械返回空列表。 */
  public static List<String> getAttachments(String gunId) {
    GunSpec spec = GUNS.get(gunId);
    return spec == null ? List.of() : spec.attachments();
  }

  private static Map<String, GunSpec> buildGuns() {
    Map<String, GunSpec> map = new HashMap<>();
    map.put("aa12", new GunSpec("tacz:12g", 8, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:muzzle_brake_mastiff_sg", "tacz:muzzle_choke_sg", "tacz:muzzle_duckbill_sg", "tacz:muzzle_silencer_sg", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("ai_awp", new GunSpec("tacz:338", 5, List.of("tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:sniper_extended_mag_1", "tacz:sniper_extended_mag_2", "tacz:sniper_extended_mag_3")));
    map.put("ak47", new GunSpec("tacz:762x39", 30, List.of("tacz:bayonet_6h3", "tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:oem_stock_heavy", "tacz:oem_stock_light", "tacz:oem_stock_tactical", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("aug", new GunSpec("tacz:556x45", 30, List.of("tacz:bayonet_m9", "tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:laser_lopro", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_aug_default", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("b93r", new GunSpec("tacz:9mm", 20, List.of("tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_wraith", "tacz:sight_acro_pistol", "tacz:sight_deltapoint_pistol", "tacz:sight_fastfire_pistol", "tacz:sight_pk06_pistol", "tacz:sight_rmr_dot", "tacz:sight_sro_dot")));
    map.put("cz75", new GunSpec("tacz:9mm", 16, List.of("tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_wraith", "tacz:sight_acro_pistol", "tacz:sight_deltapoint_pistol", "tacz:sight_fastfire_pistol", "tacz:sight_pk06_pistol", "tacz:sight_rmr_dot", "tacz:sight_sro_dot")));
    map.put("db_long", new GunSpec("tacz:12g", 2, List.of()));
    map.put("db_short", new GunSpec("tacz:12g", 2, List.of("tacz:oem_stock_tactical")));
    map.put("deagle", new GunSpec("tacz:50ae", 7, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_wraith", "tacz:scope_contender", "tacz:sight_t1")));
    map.put("deagle_golden", new GunSpec("tacz:357mag", 9, List.of("tacz:deagle_golden_long_barrel", "tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_phantom_s1", "tacz:scope_contender", "tacz:sight_t1")));
    map.put("fn_evolys", new GunSpec("tacz:308", 75, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_lopro", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("fn_fal", new GunSpec("tacz:308", 20, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("g36k", new GunSpec("tacz:556x45", 30, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("glock_17", new GunSpec("tacz:9mm", 17, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_wraith", "tacz:sight_acro_pistol", "tacz:sight_deltapoint_pistol", "tacz:sight_fastfire_pistol", "tacz:sight_pk06_pistol", "tacz:sight_rmr_dot", "tacz:sight_sro_dot")));
    map.put("hk_g3", new GunSpec("tacz:308", 20, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:oem_stock_heavy", "tacz:oem_stock_light", "tacz:oem_stock_tactical", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("hk_mk23", new GunSpec("tacz:45acp", 12, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:laser_peq6", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_wraith", "tacz:sight_acro_pistol", "tacz:sight_deltapoint_pistol", "tacz:sight_fastfire_pistol", "tacz:sight_pk06_pistol", "tacz:sight_rmr_dot", "tacz:sight_sro_dot")));
    map.put("hk_mp5a5", new GunSpec("tacz:9mm", 30, List.of("tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_ursus", "tacz:muzzle_silencer_wraith", "tacz:oem_stock_heavy", "tacz:oem_stock_light", "tacz:oem_stock_tactical", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("hk416d", new GunSpec("tacz:556x45", 30, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("kar98", new GunSpec("tacz:792x57", 4, List.of("tacz:scope_98k")));
    map.put("lonetrail", new GunSpec("tacz:30_06", 1, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("m1014", new GunSpec("tacz:12g", 6, List.of("tacz:muzzle_brake_mastiff_sg", "tacz:muzzle_choke_sg", "tacz:muzzle_duckbill_sg", "tacz:muzzle_silencer_sg", "tacz:shotgun_extended_mag_1", "tacz:shotgun_extended_mag_2", "tacz:shotgun_extended_mag_3", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("m107", new GunSpec("tacz:50bmg", 10, List.of("tacz:muzzle_silencer_vulture", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:sniper_extended_mag_1", "tacz:sniper_extended_mag_2", "tacz:sniper_extended_mag_3")));
    map.put("m16a1", new GunSpec("tacz:556x45", 20, List.of("tacz:bayonet_m9", "tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_retro_2x")));
    map.put("m16a4", new GunSpec("tacz:556x45", 30, List.of("tacz:bayonet_m9", "tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("m1911", new GunSpec("tacz:45acp", 7, List.of("tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_wraith")));
    map.put("m249", new GunSpec("tacz:556x45", 75, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_lopro", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("m4a1", new GunSpec("tacz:556x45", 30, List.of("tacz:bayonet_m9", "tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("m700", new GunSpec("tacz:30_06", 5, List.of("tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:sniper_extended_mag_1", "tacz:sniper_extended_mag_2", "tacz:sniper_extended_mag_3")));
    map.put("m870", new GunSpec("tacz:12g", 5, List.of("tacz:muzzle_brake_mastiff_sg", "tacz:muzzle_choke_sg", "tacz:muzzle_duckbill_sg", "tacz:muzzle_silencer_sg", "tacz:shotgun_extended_mag_1", "tacz:shotgun_extended_mag_2", "tacz:shotgun_extended_mag_3")));
    map.put("m95", new GunSpec("tacz:50bmg", 5, List.of("tacz:muzzle_silencer_vulture", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:sniper_extended_mag_1", "tacz:sniper_extended_mag_2", "tacz:sniper_extended_mag_3")));
    map.put("m9a4", new GunSpec("tacz:9mm", 17, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_wraith", "tacz:sight_acro_pistol", "tacz:sight_deltapoint_pistol", "tacz:sight_fastfire_pistol", "tacz:sight_pk06_pistol", "tacz:sight_rmr_dot", "tacz:sight_sro_dot")));
    map.put("mk14", new GunSpec("tacz:308", 10, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("p320", new GunSpec("tacz:45acp", 12, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_wraith", "tacz:sight_acro_pistol", "tacz:sight_deltapoint_pistol", "tacz:sight_fastfire_pistol", "tacz:sight_pk06_pistol", "tacz:sight_rmr_dot", "tacz:sight_sro_dot")));
    map.put("p90", new GunSpec("tacz:57x28", 50, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_ursus", "tacz:muzzle_silencer_wraith", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_lpvo_1_6", "tacz:scope_standard_8x", "tacz:sight_552", "tacz:sight_acro_pistol", "tacz:sight_coyote", "tacz:sight_deltapoint_pistol", "tacz:sight_exp3", "tacz:sight_fastfire_pistol", "tacz:sight_p90", "tacz:sight_pk06_pistol", "tacz:sight_rmr_dot", "tacz:sight_sro_dot", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("qbz_191", new GunSpec("tacz:58x42", 30, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("qbz_95", new GunSpec("tacz:58x42", 30, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_lopro", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("rhino357", new GunSpec("tacz:357mag", 6, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:sight_acro_rifle", "tacz:sight_deltapoint_rifle", "tacz:sight_fastfire_rifle", "tacz:sight_pk06_rifle")));
    map.put("rpk", new GunSpec("tacz:762x39", 40, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:oem_stock_heavy", "tacz:oem_stock_light", "tacz:oem_stock_tactical", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("scar_h", new GunSpec("tacz:308", 20, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("scar_l", new GunSpec("tacz:556x45", 30, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_lopro", "tacz:laser_nightstick", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("sks_tactical", new GunSpec("tacz:762x39", 10, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_lopro", "tacz:laser_peq15", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("spas_12", new GunSpec("tacz:12g", 5, List.of("tacz:muzzle_brake_mastiff_sg", "tacz:muzzle_choke_sg", "tacz:muzzle_duckbill_sg", "tacz:muzzle_silencer_sg", "tacz:shotgun_extended_mag_1", "tacz:shotgun_extended_mag_2", "tacz:shotgun_extended_mag_3", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_heavy_spas_12", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar", "tacz:stock_tactical_spas_12")));
    map.put("spr15hb", new GunSpec("tacz:556x45", 15, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_lpvo_1_6", "tacz:scope_mk5hd", "tacz:scope_qmk152", "tacz:scope_standard_8x", "tacz:scope_vudu", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    map.put("springfield1873", new GunSpec("tacz:45_70", 1, List.of("tacz:scope_1873_6x")));
    map.put("taurus500", new GunSpec("tacz:500mag", 5, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_t1")));
    map.put("timeless50", new GunSpec("tacz:50ae", 8, List.of("tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_brake_timeless50", "tacz:sight_acro_pistol", "tacz:sight_deltapoint_pistol", "tacz:sight_fastfire_pistol", "tacz:sight_pk06_pistol", "tacz:sight_rmr_dot", "tacz:sight_sro_dot")));
    map.put("type_81", new GunSpec("tacz:762x39", 30, List.of("tacz:extended_mag_1", "tacz:extended_mag_2", "tacz:extended_mag_3", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ursus")));
    map.put("ump45", new GunSpec("tacz:45acp", 25, List.of("tacz:grip_cobra", "tacz:grip_cqr", "tacz:grip_magpul_afg_2", "tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_se_5", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_ursus", "tacz:muzzle_silencer_wraith", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("uzi", new GunSpec("tacz:9mm", 20, List.of("tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_ursus", "tacz:muzzle_silencer_wraith", "tacz:scope_acog_ta31", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1")));
    map.put("vector45", new GunSpec("tacz:45acp", 20, List.of("tacz:grip_osovets_black", "tacz:grip_rk0", "tacz:grip_rk1_b25u", "tacz:grip_rk6", "tacz:grip_td", "tacz:grip_vertical_military", "tacz:grip_vertical_ranger", "tacz:grip_vertical_talon", "tacz:laser_compact", "tacz:laser_nightstick", "tacz:light_extended_mag_1", "tacz:light_extended_mag_2", "tacz:light_extended_mag_3", "tacz:muzzle_brake_cthulhu", "tacz:muzzle_brake_cyclone_d2", "tacz:muzzle_brake_pioneer", "tacz:muzzle_brake_trex", "tacz:muzzle_compensator_trident", "tacz:muzzle_silencer_knight_qd", "tacz:muzzle_silencer_mirage", "tacz:muzzle_silencer_phantom_s1", "tacz:muzzle_silencer_ptilopsis", "tacz:muzzle_silencer_ursus", "tacz:muzzle_silencer_wraith", "tacz:oem_stock_heavy", "tacz:oem_stock_tactical", "tacz:scope_acog_ta31", "tacz:scope_contender", "tacz:scope_elcan_4x", "tacz:scope_hamr", "tacz:scope_qmk152", "tacz:sight_552", "tacz:sight_acro_rifle", "tacz:sight_coyote", "tacz:sight_deltapoint_rifle", "tacz:sight_exp3", "tacz:sight_fastfire_rifle", "tacz:sight_okp7", "tacz:sight_pk06_rifle", "tacz:sight_srs_02", "tacz:sight_t2", "tacz:sight_uh1", "tacz:stock_ak12", "tacz:stock_carbon_bone_c5", "tacz:stock_hk_slim_line", "tacz:stock_m4ss", "tacz:stock_militech_b5", "tacz:stock_moe", "tacz:stock_ripstock", "tacz:stock_sba3", "tacz:stock_tactical_ar")));
    return Collections.unmodifiableMap(map);
  }
}
